package com.urfu.tgbot.enums;

public enum States {
    WAITING_FOR_COMMAND,
    WAITING_FOR_INPUT_NAME,
    WAITING_FOR_INPUT_INSTITUTE,
    WAITING_FOR_INPUT_PHONE_NUMBER,
    WAITING_FOR_INPUT_EDIT_CONFIRMATION,
    WAITING_FOR_INPUT_TIME,
    WAITING_FOR_INPUT_DESTINATION,
    WAITING_FOR_INPUT_PLACES
}
